// splashes.js
window.SPLASHES = [
"Hello World!",
"That's Numberwang!",
"XXXXXXX",
"Put that cookie down!",
"Tell your friends!",
"Play Minecraft!",
"Woo, Minecraft!",
"100% pure!",
"More polygons!",
"Finally complete!",
"Fantasy animal!",
"Handsome!",
"Nice to meet you!",
"Buckets of lava!",
"Ride the pig!",
"Larger than Earth!",
"Square again!",
"Sexy!",
"Hot tamale, hot hot tamale!",
"Play it, you'll like it!",
"Heaps of hits on YouTube!",
"Paint me like one of your Cube Girls!",
"Try it!",
"Sensational!",
"Seecret Friday update!",
"OMG secret!",
"Absolutely no memes!",
"Half a heart!",
"Feature packed!",
"Extra things!",
"Check it out!",
"Now with difficulty!",
"Enhanced!",
"Particles!",
"It's here!",
"Can't be unseen!",
"OpenGL 1.3+, not guaranteed!",
"Conventional!",
"Try the mushroom stew!",
"Llama, llama, duck!",
"Lightweight!",
"Much rejoicing!",
"Now supports multiple languages!",
"Single and multiplayer!",
"Uses LWJGL!",
"Brain++!",
"Buffered!",
"Better than Prey!",
"Leveraging synergy!",
"40% more pixels!",
"Polygonal!",
"Engage!",
"Ride the cow!",
"Inspires creativity!",
"Pretty!",
"Now in 3D!",
"Play with your friends, friends!",
"Whoa, dude!",
"More definable!",
"Generate!",
"Spread the word!",
"More sheep!",
"Play Minecraft, Watch Topgear, Get Pig!",
"Motion blur!",
"The Flash version!",
"Now with extra dimensions!",
"Wow!",
"Tip your waitresses!",
"Equipped with Diamond Armor!",
"Sapient!",
"Now in stereo!",
"Cubic!",
"Made by Notch!",
"Thanks for playing!",
"Take frequent breaks!",
"Stay hydrated!",
"HUGE!",
"Monsters in the closet!",
"Grass blocks!",
"Boats FTW!",
"Stay awhile and listen!",
"Limited edition!",
"Fight dragons!",
"Kick it root down!",
"Ghastly!",
"Spiders everywhere!",
"You have bones in your body!",
"Cue the sun!",
"Witch!",
"Rabbits steal your crops!",
"Villagers trade weird stuff!",
"Zombies lurk in the dark!",
"Exploding after some time!",
"Creeper attack!",
"Enchant your gear!",
"Dig down!",
"Mine ore!",
"Craft tools!",
"Build structures!",
"Adventure awaits!",
"Vault boy?",
"Contribute!",
"Think outside the box!",
"Boxes!",
"Such stereoscopic!",
"Awesome community!",
"Very scary!",
"Don't look behind you!",
"Spooky!",
"KAPOW!",
"Do it!",
"Don't panic!",
"AAAA!",
"What was that?",
"Welcome!",
"Boats are fast now!",
"Faster than light!",
"Direct from Sweden!",
"Keep your eyes open!",
"Gold!",
"Redstone contraptions!",
"Not AFK!",
"The Nether is hot!",
"Fill the world with blocks!",
"Pillagers raid villages!",
"Bees like flowers!",
"Buzz!",
"Honey is sticky!",
"Honey blocks are bouncy!",
"Foxes like berries!",
"Pandas like bamboo!",
"Eat cake!",
"Toast!",
"Bread is good!",
"Suspicious stew!",
"Don't dig straight down!",
"Torches prevent spawns!",
"Axolotls are cute!",
"Big drip leaf!",
"Amethyst!",
"Spyglass zoom!",
"Goat scream!",
"Powder snow is cold!",
"Copper ages!",
"Lightning rods help!",
"Glow squid glow!",
"Moss is fuzzy!",
"Caves are deep!",
"Mountains are tall!",
"Goating around!",
"Dripstone is pointy!",
"Don't stand under falling anvil!",
"Frogs!",
"Froglights!",
"Fireflies? maybe someday",
"Mangrove swamp!",
"Mud!",
"Chest boat!",
"Music makes everything better!",
"Allays help gather items!",
"Ancient city is spooky!",
"Warden can smell you!",
"Sculk spreads!",
"Goat horn!",
"Archaeology!",
"Brush off suspicious sand!",
"Pottery sherd!",
"Sniffer digs seeds!",
"Torchflower!",
"Pitcher plant!",
"Cherry grove blossoms!",
"Pink petals!",
"Camels!",
"Bamboo wood set!",
"Hanging signs!",
"Chiseled bookshelves!",
"Armor trims!",
"Smithing templates!",
"Wolf variants!",
"Bogged skeleton!",
"Trial chambers!",
"Trial spawner!",
"Ominous bottle!",
"Ominous trial spawner!",
"Hardcore!",
"Baby zombies are fast!",
"Endermen teleport!",
"Silverfish slither!",
"Shulker shell!",
"Totem of undying!",
"YOU DIED!",
"Bed too far away!",
"Cramming!",
"The cake is not a lie!",
"Herobrine?",
"Watch out for lava!",
"It’s dangerous to go alone!",
"Welcome home!",
"Welcome back!",
"Welcome newcomer!",
"More biomes!",
"Infinite worlds!",
"Basically infinite!",
"Blocks blocks blocks!",
"Stackable!",
"Minecart madness!",
"Better with friends!",
"Cookies!",
"Melons!",
"Pumpkin pie!",
"Chickens lay eggs!",
"Fish swim!",
"Cats purr!",
"Parrots dance!",
"Sheep baa!",
"Cow says moo!",
"Oink oink!",
"Neigh!",
"Bark!",
"Cluck!",
"Buzz buzz!",
"Roar!!",
"Hssssss…",
"Boom!",
"Diggy diggy hole!",
"Give us Gordon!",
"Mute the music!",
"Caves! Caves! Caves!",
"Mountains! Mountains!",
"1.21 is wild!",
"Such wow!",
"Now with more 1s and 0s!",
"Random splash!",
"Splash!",
"So splashy!",
"Breaking news!",
"Do you feel it?",
"You are the expert!",
"Trust the process!",
"Everything is cubes!",
"Emergent gameplay!",
"Redstone engineering!",
"Blocky goodness!",
"Home sweet home!",
"Did you know?",
"Unbelievable!",
"You’re doing great!",
"Neat!",
"Cool beans!",
"Smooth!",
"Pardon our dust!",
"Beta testing!",
"Now with 99% fewer bugs!",
"Now with more bugs!",
"Under development!",
"Work in progress!",
"Beyond your imagination!",
"Infinite possibilities!",
"Yes, it's still Minecraft!",
"Restart required!",
"Don’t forget to sleep!",
"Sweet dreams!",
"Made with love!",
"Java rules!",
"Blocktacular!",
"Everything is fine!"
];
